// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CustomerInterface.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SharedInterface.Interfaces.CustomInterface {

  /// <summary>Holder for reflection information generated from CustomerInterface.proto</summary>
  public static partial class CustomerInterfaceReflection {

    #region Descriptor
    /// <summary>File descriptor for CustomerInterface.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CustomerInterfaceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdDdXN0b21lckludGVyZmFjZS5wcm90bxIPU2hhcmVkSW50ZXJmYWNlGh9D",
            "dXN0b21lckludGVyZmFjZU1lc3NhZ2VzLnByb3RvMs8DChFDdXN0b21lcklu",
            "dGVyZmFjZRJdChBPcGVuQWNjb3VudEFzeW5jEiMuU2hhcmVkSW50ZXJmYWNl",
            "Lk9wZW5BY2NvdW50UmVxdWVzdBokLlNoYXJlZEludGVyZmFjZS5PcGVuQWNj",
            "b3VudFJlc3BvbnNlElQKDVdpdGhkcmF3QXN5bmMSIC5TaGFyZWRJbnRlcmZh",
            "Y2UuV2l0aGRyYXdSZXF1ZXN0GiEuU2hhcmVkSW50ZXJmYWNlLldpdGhkcmF3",
            "UmVzcG9uc2USRwoMRGVwb3NpdEFzeW5jEh8uU2hhcmVkSW50ZXJmYWNlLkRl",
            "cG9zaXRSZXF1ZXN0GhYuU2hhcmVkSW50ZXJmYWNlLkVtcHR5EloKD0dldEhp",
            "c3RvcnlBc3luYxIiLlNoYXJlZEludGVyZmFjZS5HZXRIaXN0b3J5UmVxdWVz",
            "dBojLlNoYXJlZEludGVyZmFjZS5HZXRIaXN0b3J5UmVzcG9uc2USYAoRQ2xv",
            "c2VBY2NvdW50QXN5bmMSJC5TaGFyZWRJbnRlcmZhY2UuQ2xvc2VBY2NvdW50",
            "UmVxdWVzdBolLlNoYXJlZEludGVyZmFjZS5DbG9zZUFjY291bnRSZXNwb25z",
            "ZUItqgIqU2hhcmVkSW50ZXJmYWNlLkludGVyZmFjZXMuQ3VzdG9tSW50ZXJm",
            "YWNlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SharedInterface.Interfaces.CustomInterface.CustomerInterfaceMessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
