// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: InspectorInterface.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace SharedInterface.Interfaces.InspectorInterface {
  public static partial class InspectorInterface
  {
    static readonly string __ServiceName = "InspectorInterface.InspectorInterface";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::SharedInterface.Interfaces.InspectorInterface.Empty> __Marshaller_InspectorInterface_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SharedInterface.Interfaces.InspectorInterface.Empty.Parser));
    static readonly grpc::Marshaller<global::SharedInterface.Interfaces.InspectorInterface.GetFullSummaryResponse> __Marshaller_InspectorInterface_GetFullSummaryResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SharedInterface.Interfaces.InspectorInterface.GetFullSummaryResponse.Parser));

    static readonly grpc::Method<global::SharedInterface.Interfaces.InspectorInterface.Empty, global::SharedInterface.Interfaces.InspectorInterface.GetFullSummaryResponse> __Method_GetFullSummaryAsync = new grpc::Method<global::SharedInterface.Interfaces.InspectorInterface.Empty, global::SharedInterface.Interfaces.InspectorInterface.GetFullSummaryResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetFullSummaryAsync",
        __Marshaller_InspectorInterface_Empty,
        __Marshaller_InspectorInterface_GetFullSummaryResponse);

    static readonly grpc::Method<global::SharedInterface.Interfaces.InspectorInterface.Empty, global::SharedInterface.Interfaces.InspectorInterface.Empty> __Method_StartInspectionAsync = new grpc::Method<global::SharedInterface.Interfaces.InspectorInterface.Empty, global::SharedInterface.Interfaces.InspectorInterface.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartInspectionAsync",
        __Marshaller_InspectorInterface_Empty,
        __Marshaller_InspectorInterface_Empty);

    static readonly grpc::Method<global::SharedInterface.Interfaces.InspectorInterface.Empty, global::SharedInterface.Interfaces.InspectorInterface.Empty> __Method_FinishInspectionAsync = new grpc::Method<global::SharedInterface.Interfaces.InspectorInterface.Empty, global::SharedInterface.Interfaces.InspectorInterface.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "FinishInspectionAsync",
        __Marshaller_InspectorInterface_Empty,
        __Marshaller_InspectorInterface_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SharedInterface.Interfaces.InspectorInterface.InspectorInterfaceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of InspectorInterface</summary>
    [grpc::BindServiceMethod(typeof(InspectorInterface), "BindService")]
    public abstract partial class InspectorInterfaceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::SharedInterface.Interfaces.InspectorInterface.GetFullSummaryResponse> GetFullSummaryAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SharedInterface.Interfaces.InspectorInterface.Empty> StartInspectionAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SharedInterface.Interfaces.InspectorInterface.Empty> FinishInspectionAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for InspectorInterface</summary>
    public partial class InspectorInterfaceClient : grpc::ClientBase<InspectorInterfaceClient>
    {
      /// <summary>Creates a new client for InspectorInterface</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public InspectorInterfaceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for InspectorInterface that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public InspectorInterfaceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected InspectorInterfaceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected InspectorInterfaceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::SharedInterface.Interfaces.InspectorInterface.GetFullSummaryResponse GetFullSummaryAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFullSummaryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SharedInterface.Interfaces.InspectorInterface.GetFullSummaryResponse GetFullSummaryAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetFullSummaryAsync, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SharedInterface.Interfaces.InspectorInterface.GetFullSummaryResponse> GetFullSummaryAsyncAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFullSummaryAsyncAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SharedInterface.Interfaces.InspectorInterface.GetFullSummaryResponse> GetFullSummaryAsyncAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetFullSummaryAsync, null, options, request);
      }
      public virtual global::SharedInterface.Interfaces.InspectorInterface.Empty StartInspectionAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartInspectionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SharedInterface.Interfaces.InspectorInterface.Empty StartInspectionAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StartInspectionAsync, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SharedInterface.Interfaces.InspectorInterface.Empty> StartInspectionAsyncAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartInspectionAsyncAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SharedInterface.Interfaces.InspectorInterface.Empty> StartInspectionAsyncAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StartInspectionAsync, null, options, request);
      }
      public virtual global::SharedInterface.Interfaces.InspectorInterface.Empty FinishInspectionAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FinishInspectionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SharedInterface.Interfaces.InspectorInterface.Empty FinishInspectionAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_FinishInspectionAsync, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SharedInterface.Interfaces.InspectorInterface.Empty> FinishInspectionAsyncAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FinishInspectionAsyncAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SharedInterface.Interfaces.InspectorInterface.Empty> FinishInspectionAsyncAsync(global::SharedInterface.Interfaces.InspectorInterface.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_FinishInspectionAsync, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override InspectorInterfaceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new InspectorInterfaceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(InspectorInterfaceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetFullSummaryAsync, serviceImpl.GetFullSummaryAsync)
          .AddMethod(__Method_StartInspectionAsync, serviceImpl.StartInspectionAsync)
          .AddMethod(__Method_FinishInspectionAsync, serviceImpl.FinishInspectionAsync).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, InspectorInterfaceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetFullSummaryAsync, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SharedInterface.Interfaces.InspectorInterface.Empty, global::SharedInterface.Interfaces.InspectorInterface.GetFullSummaryResponse>(serviceImpl.GetFullSummaryAsync));
      serviceBinder.AddMethod(__Method_StartInspectionAsync, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SharedInterface.Interfaces.InspectorInterface.Empty, global::SharedInterface.Interfaces.InspectorInterface.Empty>(serviceImpl.StartInspectionAsync));
      serviceBinder.AddMethod(__Method_FinishInspectionAsync, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SharedInterface.Interfaces.InspectorInterface.Empty, global::SharedInterface.Interfaces.InspectorInterface.Empty>(serviceImpl.FinishInspectionAsync));
    }

  }
}
#endregion
