// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: InspectorInterface.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SharedInterface.Interfaces.InspectorInterface {

  /// <summary>Holder for reflection information generated from InspectorInterface.proto</summary>
  public static partial class InspectorInterfaceReflection {

    #region Descriptor
    /// <summary>File descriptor for InspectorInterface.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InspectorInterfaceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhJbnNwZWN0b3JJbnRlcmZhY2UucHJvdG8SEkluc3BlY3RvckludGVyZmFj",
            "ZRogSW5zcGVjdG9ySW50ZXJmYWNlTWVzc2FnZXMucHJvdG8yjwIKEkluc3Bl",
            "Y3RvckludGVyZmFjZRJcChNHZXRGdWxsU3VtbWFyeUFzeW5jEhkuSW5zcGVj",
            "dG9ySW50ZXJmYWNlLkVtcHR5GiouSW5zcGVjdG9ySW50ZXJmYWNlLkdldEZ1",
            "bGxTdW1tYXJ5UmVzcG9uc2USTAoUU3RhcnRJbnNwZWN0aW9uQXN5bmMSGS5J",
            "bnNwZWN0b3JJbnRlcmZhY2UuRW1wdHkaGS5JbnNwZWN0b3JJbnRlcmZhY2Uu",
            "RW1wdHkSTQoVRmluaXNoSW5zcGVjdGlvbkFzeW5jEhkuSW5zcGVjdG9ySW50",
            "ZXJmYWNlLkVtcHR5GhkuSW5zcGVjdG9ySW50ZXJmYWNlLkVtcHR5QjCqAi1T",
            "aGFyZWRJbnRlcmZhY2UuSW50ZXJmYWNlcy5JbnNwZWN0b3JJbnRlcmZhY2Vi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SharedInterface.Interfaces.InspectorInterface.InspectorInterfaceMessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
